apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          command: ["/bin/bash", "-c", "gunicorn -c conf.py main:app && tail -f /dev/null"]
          restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort